[project]
name = "mewline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fabric",
    "loguru>=0.7.3",
    "psutil>=6.1.1",
    "pydantic>=2.10.6",
    "setproctitle>=1.3.4",
]

[project.urls]
Homepage = "https://github.com/meowrch/mewline"
Documentation = "https://github.com/meowrch/mewline/wiki"
Repository = "https://github.com/meowrch/mewline.git"
"Bug Tracker" = "https://github.com/meowrch/mewline/issues"
Changelog = "https://github.com/meowrch/mewline/blob/master/CHANGELOG.md"

[project.scripts]
generate = "mewline.__main__:generate"
mewline = "mewline.__main__:main"

[tool.uv]
package=true

[tool.uv.sources]
fabric = { git = "https://github.com/Fabric-Development/fabric.git" }

[tool.ruff]
target-version = "py311"
line-length = 70
